// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8XtBQ-Shxl7vRTC3jszCP_2mndBhYszQ',
    appId: '1:572101092025:web:221021ead1673b1758f168',
    messagingSenderId: '572101092025',
    projectId: 'worldskills-f6-1',
    authDomain: 'worldskills-f6-1.firebaseapp.com',
    databaseURL: 'https://worldskills-f6-1.firebaseio.com',
    storageBucket: 'worldskills-f6-1.appspot.com',
    measurementId: 'G-6GSZTQTX06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDS03TN-gE_RcTx_m-F43xEK324q7l9s',
    appId: '1:572101092025:android:202acd4eb564f19e58f168',
    messagingSenderId: '572101092025',
    projectId: 'worldskills-f6-1',
    databaseURL: 'https://worldskills-f6-1.firebaseio.com',
    storageBucket: 'worldskills-f6-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmVtWf-rMLXuK5mxK4P0sGwtaqhVvae94',
    appId: '1:572101092025:ios:e005b5e38304c4c658f168',
    messagingSenderId: '572101092025',
    projectId: 'worldskills-f6-1',
    databaseURL: 'https://worldskills-f6-1.firebaseio.com',
    storageBucket: 'worldskills-f6-1.appspot.com',
    androidClientId: '572101092025-46858tkbul7skkud666km0b273fajarp.apps.googleusercontent.com',
    iosClientId: '572101092025-vi3c2blspd7fip0e9ktg65vuna9h0ruq.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocCrypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmVtWf-rMLXuK5mxK4P0sGwtaqhVvae94',
    appId: '1:572101092025:ios:e005b5e38304c4c658f168',
    messagingSenderId: '572101092025',
    projectId: 'worldskills-f6-1',
    databaseURL: 'https://worldskills-f6-1.firebaseio.com',
    storageBucket: 'worldskills-f6-1.appspot.com',
    androidClientId: '572101092025-46858tkbul7skkud666km0b273fajarp.apps.googleusercontent.com',
    iosClientId: '572101092025-vi3c2blspd7fip0e9ktg65vuna9h0ruq.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocCrypto',
  );
}
